@E_Commerce_with_Integreted_Seller_Dashboard_Comp313_003_HostAddress = http://localhost:5047

GET {{E_Commerce_with_Integreted_Seller_Dashboard_Comp313_003_HostAddress}}/weatherforecast/
Accept: application/json

###
